name: serverless CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


env:
  REGION: cn-shanghai

jobs:
  serverless-cicd-job:
    name: Serverless cicd
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initializing Serverless-Devs
      uses: Serverless-Devs/serverless-devs-initialization-action@v1
      with:
        AccessKeyID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        AccessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        AccountID: ${{ secrets.ALIYUN_ACCOUNT_ID }}