# This workflow will Install Serverless Devs.

name: Serverless Devs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# This is comment
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      run: docker info
      shell: bash
