name: Say hello!

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    strategy:
      matrix:
        jobId: [1, 2, 3]
    steps:
    - name: step matrix
      run: echo ${{ matrix.jobId }}